name: todoapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-60.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash: 
  image: lib/assets/logo.png
  color: "#E1D4C8"
  scale_type: "centerCrop"
  android_12: 
    image: lib/assets/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  adaptive_icon_background: "#E1D4C8"
  adaptive_icon_foreground: "lib/assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/no_notes.png
    - lib/assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700